### ISSUE TITLE
Unauthenticated User Exception

### ISSUE THREAD

**Issue by fatpacket** [microsoftgraph/msgraph-sample-pythondjangoapp#85]
### Where did you get the code?

- [ ] Downloaded from GitHub
- [X] Downloaded from the [Microsoft Graph quick start tool](https://developer.microsoft.com/graph/quick-start)
- [X] Followed the tutorial from [Microsoft Graph tutorials](https://docs.microsoft.com/graph/tutorials)

### Describe the bug

Unauthenticated attempt to access localhost:8000/calendar directly generates a traceback line 75 in views.py
time_zone = get_iana_from_windows(user['timeZone']) 
This makes sense as the there is no way to grab the user session for TZ

### To Reproduce

1. Navigate to localhost:8000
2. Do NOT log in
3. append /calendar to the url --> http://localhost:8000/calendar
4. Error appears

### Expected behavior

I would thing there is or should be an is authenticated check in the view and if not it would redirect back to the home page.
Is there a way to implement that in views.py as opposed to the hard coding it in the HTML page. Some sort of decorator applied to the def calendar(request).  Not sure @login_required would work here since we are using msal vs the default django system??  Or would user_passes_test be an option.  (https://www.adamsmith.haus/python/docs/django.contrib.auth.decorators.user_passes_test)
I would like to implement it myself in the code but I am not that smart and just learning from these tutorials

### Desktop

OS - Windows 10 64bit
Browser - Chrome 
Version - 99.0.4844.51

### Dependency versions

- Authentication library msal==1.10.0
- Graph library (Graph SDK, REST library, etc.) version:

### Additional context

Maybe this falls under feature request but was hoping it was an easy addition to the code

**Comment by fatpacket** [comment]
Similar issue with /calendar/new
The get request renders the event form but on submission throws the same error.
An is_authenticated or user_passes_test decorator to prevent unauthenticated access

Thank you for the help

**Comment by jasonjoh** [comment]
You're right that this isn't integrating with Django's auth system, so those decorators won't work. The simplest way I see given the current implementation would be to add something like this to the views after loading the `user` from the context:

```python
if not user['is_authenticated']:
    return HttpResponseRedirect(reverse('signin'))
```
